Dl 15 create stall product form
OgryzekTM/corona-market pull request #38
Opened 2020-10-06 22:33 UTC by darialasecka

2020-10-07 17:30 UTC, urszulasologub requested changes
Overall - good job. I'm really glad you fixed my background, but I also think there's some room for improvements. Especially, because the front-end of our application is somehow a key feature and it's even more important than making it work, because the audience will only see its look, not the way it works. So any fancy css or other tricks would be great

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/StallCard/index.js
> +          <br />
Can we remove those `<br />` markers? We can use css or different components if we want to add more space

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/StallCard/index.js
> +          <p> Description </p>
Please, create separate component for labels instead of using `<p>`, so we can easily add style to it

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/StallCard/index.js
> +          <p> Description </p>
I also believe it would look more aesthetic if labels were in the same rows as inputs.

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/StallCard/index.js
> +          <Input value="Description" type="text" />
I think this input is way too small. Rarely people use such small inputs for such long texts as description. I think you can create new component for that very easily - the same way as I did with Button and SpecialButton, where SpecialButton kinda "inherits" Button's css

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/StallCard/index.js
> +          <Input value="Shipping price" />
I think such inputs like price (and maybe also phone number) shouldn't allow anyone to enter characters that aren't numerical. I think this would do the job: 
```suggestion
          <Input value="Shipping price" type="number" />
```
Please, look at this page, since I believe it may help you with different inputs: https://www.w3schools.com/html/html_form_input_types.asp
If my component doesn't accept something (like min and max values), just pass it in `Input/index.js`

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/StallCard/index.js
> +          <Input value="Phone number" type="text" /> <br />
The type shouldn't be text

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/StallCard/index.js
> +          <Checkbox id="public" onClick={handlePublic}>
I believe we can remove this checkbox. is_public is a field that says if a stall should be visible to users or not, users shouldn't be able to change it

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/StallCard/index.js
> +          <p> City </p>
Can we change the order of the fields to make them more logical? I don't think [City, Description, Photo, isShipping, Name, shippingPrice, phoneNumber] is anyhow user-friendly order. Wouldn't [Name, Description, Photo, City, phoneNumber, isShipping { if it is -> shippingPrice, otherwise it may be disabled}] make more sense?

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/ProductCard/index.js
> +          <br />
Please, look at comments at `app/src/containers/StallCard/index.js` and adjust them to this form

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/ProductCard/index.js
> +            Is Available{' '}
I think this checkbox is unecessary. This option would be available to the seller if he run out of products, you can remove it

2020-10-07 17:30 UTC, urszulasologub commented on app/src/components/Select/styledComponents.js
> +export const StyledSelect = styled.select`
![image](https://user-images.githubusercontent.com/34507753/95365230-27decf80-08d2-11eb-969e-127fd5ad9161.png)
I think you can try to find in Google some interesting stylings for selectors. I don't really like this "bird" thing on the right - it just looks so not modern

2020-10-07 17:30 UTC, urszulasologub commented on app/src/components/Option/styledComponents.js
> +  padding: 0.5em 0.5em;
I think it needs some additional styling to match selector

2020-10-07 17:30 UTC, urszulasologub commented on app/src/components/FileUpload/index.js
> +    <StyledFileUpload id="file-upload" type="file" inputProps={{ accept: 'image/*' }} />
I believe `id` is something that should be unique, so wouldn't it be better if a programmer could pass it as argument?
```suggestion
  <Label for={fileUploadId} class="custom-file-upload">
    <StyledFileUpload id={fileUploadId} type="file" inputProps={{ accept: 'image/*' }} />
```

2020-10-07 17:30 UTC, urszulasologub commented on app/src/components/FileUpload/styledComponents.js
> +  display: none;
![image](https://user-images.githubusercontent.com/34507753/95365775-df73e180-08d2-11eb-99b9-82e2449c61af.png)
![image](https://user-images.githubusercontent.com/34507753/95365789-e39fff00-08d2-11eb-8a9c-5c809c73120e.png)
I don't think this filepicker really matches buttons. They look inconsistently.

2020-10-07 17:30 UTC, urszulasologub commented on app/src/containers/ProductCard/index.js
> +          <FileUpload /> <br />
Forgive me forgetting to mention that earlier, but wouldn't it be nicer if FileUpload had any kind of indicator saying if file was submitted? Like label with filename next to the filepicker or something like that?

2020-10-07 22:08 UTC, DawidCwiek commented
I will resolve these conflicts

2020-10-08 16:27 UTC, urszulasologub approved these changes

2020-10-08 16:27 UTC, merged